### ISSUE TITLE
Updating the v1 tag

### ISSUE THREAD

**Issue by sol** [haskell-actions/hackage-publish#4]
@AlexeyRaga can you update `v1` to include my recent changes to `master` (I'm assuming that `v1` is meant to be a sliding tag)?

**Comment by AlexeyRaga** [comment]
I much prefer published versions to be immutable (at least so far) so I published `v1.1` instead :)

**Comment by sol** [comment]
> I much prefer published versions to be immutable

That makes sense, yes.

I guess the only downside I can come up with is that the official GitHub actions do not treat `v1` immutable.  Having used other actions before, I'm used to the convention that I can say `v1` and always get the latest changes of the `v1` branch (basically emulating something like `== 1.*` with git tags).

**Comment by AlexeyRaga** [comment]
Hmmm, I didn't know that. Not sure how to feel about it, but if this is their "official" guideline then probably we should listen... :-/
